### ISSUE TITLE
More non trivial examples

### ISSUE THREAD

**Issue by mingodad** [EricLengyel/OpenDDL#3]
I've just added one `OpenDDL` grammar to https://mingodad.github.io/parsertl-playground/playground/ an `Yacc/lex` compatible online editor/tester (select `Openddl parser` from `Examples` then click `Parse` to see a parser tree of the content in `Input source`) and I've noticed that there isn't enough non trivial examples to test the specification.

Do you know/have more examples ?

**Comment by EricLengyel** [comment]
Are you familiar with OpenGEX?

https://github.com/EricLengyel/OpenGEX

**Comment by mingodad** [comment]
Thank you for reply !
That example is better than nothing but still it's not enough to test with confidence.
